# GolangCI-Lint configuration for Cluso GraphDB
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Enabled by default
    - errcheck     # Check for unchecked errors
    - gosimple     # Simplify code
    - govet        # Reports suspicious constructs
    - ineffassign  # Detect ineffectual assignments
    - staticcheck  # Go static analysis
    - unused       # Check for unused constants, variables, functions

    # Additional important linters
    - gofmt        # Check code is gofmt-ed
    - goimports    # Check import formatting
    - misspell     # Check for misspelled English words
    - revive       # Fast, configurable, extensible linter
    - gosec        # Security checks
    - gocritic     # Comprehensive Go source code linter
    - unconvert    # Remove unnecessary type conversions
    - nakedret     # Find naked returns in functions

  disable:
    - typecheck    # Can be problematic with generics
    - predeclared  # Too strict for demonstration code
    - unparam      # Too strict for demonstration code
    - gocyclo      # Too strict for demonstration code
    - dupl         # Too strict for demonstration code
    - goconst      # Too strict for demonstration code
    - godot        # Too pedantic about comment periods

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*github.com/dd0wney/cluso-graphdb/pkg/storage.GraphStorage).GetOutgoingEdges
      - (*github.com/dd0wney/cluso-graphdb/pkg/storage.GraphStorage).GetIncomingEdges
      - (*github.com/dd0wney/cluso-graphdb/pkg/storage.GraphStorage).GetNode
      - (*github.com/dd0wney/cluso-graphdb/pkg/lsm.Compactor).CleanupOldSSTables
      - (*github.com/dd0wney/cluso-graphdb/pkg/lsm.LSMStorage).compact
      - encoding/binary.Read
      - (*github.com/dd0wney/cluso-graphdb/pkg/lsm.BlockCache).evict
      - (*github.com/dd0wney/cluso-graphdb/pkg/lsm.BlockCache).Put

  govet:
    enable-all: true
    disable:
      - shadow  # Can be too strict
      - fieldalignment  # Optimization not critical for this codebase

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/dd0wney/cluso-graphdb

  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: indent-error-flow
        severity: warning

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G404  # Use of weak random number generator (math/rand)

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  dupl:
    threshold: 100

  nakedret:
    max-func-lines: 30

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude benchmark/cmd files from strict linting (demonstration code)
    - path: cmd/
      linters:
        - gocyclo
        - dupl
        - errcheck
        - gocritic
        - goimports
        - staticcheck
        - unused

    # Ignore long lines in go:generate
    - linters:
        - lll
      source: "^//go:generate "

  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 3

  # Show only new issues
  new: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
