# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-04T11:34:06+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional


class Role(Enum):
    admin = 'admin'
    editor = 'editor'
    viewer = 'viewer'


@dataclass
class User:
    id: Optional[str] = None
    username: Optional[str] = None
    role: Optional[Role] = None
    created_at: Optional[int] = None


@dataclass
class Node:
    id: Optional[int] = None
    labels: Optional[List[str]] = None
    properties: Optional[Dict[str, Any]] = None


@dataclass
class Edge:
    id: Optional[int] = None
    from_node_id: Optional[int] = None
    to_node_id: Optional[int] = None
    type: Optional[str] = None
    weight: Optional[float] = None
    properties: Optional[Dict[str, Any]] = None


@dataclass
class Error:
    error: Optional[str] = None
    code: Optional[str] = None
    details: Optional[Dict[str, Any]] = None


class Metric(Enum):
    cosine = 'cosine'
    euclidean = 'euclidean'
    dot_product = 'dot_product'


@dataclass
class VectorIndexRequest:
    property_name: str
    dimensions: int
    m: Optional[int] = 16
    ef_construction: Optional[int] = 200
    metric: Optional[Metric] = Metric.cosine


@dataclass
class VectorIndexResponse:
    property_name: Optional[str] = None
    dimensions: Optional[int] = None
    metric: Optional[str] = None


@dataclass
class VectorIndexListResponse:
    indexes: Optional[List[VectorIndexResponse]] = None
    count: Optional[int] = None


@dataclass
class VectorSearchRequest:
    property_name: str
    query_vector: List[float]
    k: int
    ef: Optional[int] = None
    include_nodes: Optional[bool] = False
    filter_labels: Optional[List[str]] = None


@dataclass
class VectorSearchResult:
    node_id: Optional[int] = None
    distance: Optional[float] = None
    score: Optional[float] = None
    node: Optional[Node] = None


@dataclass
class VectorSearchResponse:
    results: Optional[List[VectorSearchResult]] = None
    count: Optional[int] = None
    took_ms: Optional[int] = None


@dataclass
class SearchRequest:
    query: str
    limit: Optional[int] = None
    offset: Optional[int] = None
    labels: Optional[List[str]] = None
    include_content: Optional[bool] = None
    include_nodes: Optional[bool] = None


@dataclass
class SearchResultItem:
    node_id: Optional[int] = None
    score: Optional[float] = None
    snippet: Optional[str] = None
    node: Optional[Node] = None


@dataclass
class SearchResponse:
    results: Optional[List[SearchResultItem]] = None
    count: Optional[int] = None
    took_ms: Optional[int] = None


@dataclass
class HybridSearchRequest:
    query: str
    limit: Optional[int] = None
    offset: Optional[int] = None
    labels: Optional[List[str]] = None
    alpha: Optional[float] = None
    include_content: Optional[bool] = None
    include_nodes: Optional[bool] = None


@dataclass
class HybridSearchResultItem:
    node_id: Optional[int] = None
    score: Optional[float] = None
    fts_rank: Optional[int] = None
    lsa_rank: Optional[int] = None
    snippet: Optional[str] = None
    node: Optional[Node] = None


class Degraded(Enum):
    no_lsa_index = 'no-lsa-index'
    query_out_of_vocabulary = 'query-out-of-vocabulary'
    field_ = ''


@dataclass
class HybridSearchResponse:
    results: Optional[List[HybridSearchResultItem]] = None
    count: Optional[int] = None
    took_ms: Optional[int] = None
    degraded: Optional[Degraded] = None


@dataclass
class SearchIndexRequest:
    labels: List[str]
    properties: List[str]


@dataclass
class SearchIndexResponse:
    indexed_nodes: Optional[int] = None
    took_ms: Optional[int] = None


@dataclass
class LSAIndexRequest:
    labels: List[str]
    body_properties: List[str]
    title_property: Optional[str] = None
    dims: Optional[int] = None
    min_doc_freq: Optional[int] = None
    max_vocab: Optional[int] = None
    title_boost: Optional[int] = None
    seed: Optional[int] = None


@dataclass
class LSAIndexResponse:
    indexed_docs: Optional[int] = None
    dimensions: Optional[int] = None
    took_ms: Optional[int] = None
