{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "graphdb.fullname" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "graphdb.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.config.tls.enabled }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
{{- end }}
