// Package models provides OT network model definitions.
package models

// TelecomProviderNodes defines all 114 nodes for the Telecom Provider model.
// Demonstrates cross-sector critical infrastructure dependencies and the invisible
// node pattern at scale. The telecom sector is the "infrastructure of infrastructures".
var TelecomProviderNodes = []NodeDef{
	// Core Network (9)
	{"Core_Router_SYD", []string{"Technical", "Router", "MPLS"}, "Core_Network", NodeTypeTechnical, "MPLS backbone routing"},
	{"Core_Router_MEL", []string{"Technical", "Router", "MPLS"}, "Core_Network", NodeTypeTechnical, "MPLS backbone routing"},
	{"Core_Router_BNE", []string{"Technical", "Router", "MPLS"}, "Core_Network", NodeTypeTechnical, "MPLS backbone routing"},
	{"Core_Router_PER", []string{"Technical", "Router", "MPLS"}, "Core_Network", NodeTypeTechnical, "MPLS backbone routing"},
	{"Core_Router_ADL", []string{"Technical", "Router", "MPLS"}, "Core_Network", NodeTypeTechnical, "MPLS backbone routing"},
	{"DWDM_SYD_MEL", []string{"Technical", "Optical"}, "Core_Network", NodeTypeTechnical, "Optical transport"},
	{"DWDM_SYD_BNE", []string{"Technical", "Optical"}, "Core_Network", NodeTypeTechnical, "Optical transport"},
	{"DWDM_MEL_ADL", []string{"Technical", "Optical"}, "Core_Network", NodeTypeTechnical, "Optical transport"},
	{"DWDM_ADL_PER", []string{"Technical", "Optical"}, "Core_Network", NodeTypeTechnical, "Optical transport"},

	// Mobile Core (8)
	{"MME_Primary", []string{"Technical", "MobileCore"}, "Mobile_Core", NodeTypeTechnical, "Mobile network core"},
	{"MME_Secondary", []string{"Technical", "MobileCore"}, "Mobile_Core", NodeTypeTechnical, "Mobile network core"},
	{"SGW_Primary", []string{"Technical", "MobileCore"}, "Mobile_Core", NodeTypeTechnical, "Mobile network core"},
	{"SGW_Secondary", []string{"Technical", "MobileCore"}, "Mobile_Core", NodeTypeTechnical, "Mobile network core"},
	{"PGW_Primary", []string{"Technical", "MobileCore"}, "Mobile_Core", NodeTypeTechnical, "Mobile network core"},
	{"PGW_Secondary", []string{"Technical", "MobileCore"}, "Mobile_Core", NodeTypeTechnical, "Mobile network core"},
	{"HSS_Primary", []string{"Technical", "MobileCore"}, "Mobile_Core", NodeTypeTechnical, "Mobile network core"},
	{"IMS_Core", []string{"Technical", "MobileCore"}, "Mobile_Core", NodeTypeTechnical, "Mobile network core"},

	// Access Network (19)
	{"Exchange_CBD", []string{"Technical", "Exchange"}, "Access_Network", NodeTypeTechnical, "Local exchange"},
	{"Exchange_North", []string{"Technical", "Exchange"}, "Access_Network", NodeTypeTechnical, "Local exchange"},
	{"Exchange_South", []string{"Technical", "Exchange"}, "Access_Network", NodeTypeTechnical, "Local exchange"},
	{"Exchange_West", []string{"Technical", "Exchange"}, "Access_Network", NodeTypeTechnical, "Local exchange"},
	{"Exchange_Industrial", []string{"Technical", "Exchange"}, "Access_Network", NodeTypeTechnical, "Local exchange"},
	{"Cell_CBD_1", []string{"Technical", "CellSite"}, "Access_Network", NodeTypeTechnical, "Cell site/base station"},
	{"Cell_CBD_2", []string{"Technical", "CellSite"}, "Access_Network", NodeTypeTechnical, "Cell site/base station"},
	{"Cell_CBD_3", []string{"Technical", "CellSite"}, "Access_Network", NodeTypeTechnical, "Cell site/base station"},
	{"Cell_Suburban_1", []string{"Technical", "CellSite"}, "Access_Network", NodeTypeTechnical, "Cell site/base station"},
	{"Cell_Suburban_2", []string{"Technical", "CellSite"}, "Access_Network", NodeTypeTechnical, "Cell site/base station"},
	{"Cell_Regional_1", []string{"Technical", "CellSite"}, "Access_Network", NodeTypeTechnical, "Cell site/base station"},
	{"Cell_Regional_2", []string{"Technical", "CellSite"}, "Access_Network", NodeTypeTechnical, "Cell site/base station"},
	{"Cell_Hospital", []string{"Technical", "CellSite"}, "Access_Network", NodeTypeTechnical, "Cell site/base station"},
	{"Cell_Emergency_HQ", []string{"Technical", "CellSite"}, "Access_Network", NodeTypeTechnical, "Cell site/base station"},
	{"FDH_CBD", []string{"Technical", "FibreDistribution"}, "Access_Network", NodeTypeTechnical, "Fibre distribution"},
	{"FDH_Business_Park", []string{"Technical", "FibreDistribution"}, "Access_Network", NodeTypeTechnical, "Fibre distribution"},
	{"FDH_Hospital", []string{"Technical", "FibreDistribution"}, "Access_Network", NodeTypeTechnical, "Fibre distribution"},
	{"FDH_Gov_Precinct", []string{"Technical", "FibreDistribution"}, "Access_Network", NodeTypeTechnical, "Fibre distribution"},
	{"FDH_Data_Centre", []string{"Technical", "FibreDistribution"}, "Access_Network", NodeTypeTechnical, "Fibre distribution"},

	// NOC (7)
	{"NMS_Primary", []string{"Technical", "NetworkManagement"}, "NOC", NodeTypeTechnical, "Network operations"},
	{"NMS_Secondary", []string{"Technical", "NetworkManagement"}, "NOC", NodeTypeTechnical, "Network operations"},
	{"NOC_Dashboard", []string{"Technical", "Dashboard"}, "NOC", NodeTypeTechnical, "Network operations"},
	{"Fault_Mgmt_System", []string{"Technical", "FaultManagement"}, "NOC", NodeTypeTechnical, "Network operations"},
	{"Performance_Monitor", []string{"Technical", "Monitoring"}, "NOC", NodeTypeTechnical, "Network operations"},
	{"SIEM_Telecom", []string{"Technical", "Security"}, "NOC", NodeTypeTechnical, "Network operations"},
	{"Ticketing_System", []string{"Technical", "ServiceDesk"}, "NOC", NodeTypeTechnical, "Network operations"},

	// BSS/OSS (9)
	{"Billing_System", []string{"Technical", "BSS"}, "BSS_OSS", NodeTypeTechnical, "Business/operations support"},
	{"CRM_System", []string{"Technical", "BSS"}, "BSS_OSS", NodeTypeTechnical, "Business/operations support"},
	{"Provisioning_System", []string{"Technical", "OSS"}, "BSS_OSS", NodeTypeTechnical, "Business/operations support"},
	{"Inventory_System", []string{"Technical", "OSS"}, "BSS_OSS", NodeTypeTechnical, "Business/operations support"},
	{"Workforce_Mgmt", []string{"Technical", "OSS"}, "BSS_OSS", NodeTypeTechnical, "Business/operations support"},
	{"DNS_Primary", []string{"Technical", "DNS"}, "BSS_OSS", NodeTypeTechnical, "Business/operations support"},
	{"DNS_Secondary", []string{"Technical", "DNS"}, "BSS_OSS", NodeTypeTechnical, "Business/operations support"},
	{"AAA_Server", []string{"Technical", "Authentication"}, "BSS_OSS", NodeTypeTechnical, "Business/operations support"},
	{"RADIUS_Server", []string{"Technical", "Authentication"}, "BSS_OSS", NodeTypeTechnical, "Business/operations support"},

	// Corporate IT (6)
	{"Corp_Firewall", []string{"Technical", "Firewall"}, "Corporate_IT", NodeTypeTechnical, "Corporate IT systems"},
	{"IT_Switch_Core", []string{"Technical", "NetworkSwitch"}, "Corporate_IT", NodeTypeTechnical, "Corporate IT systems"},
	{"Corp_AD", []string{"Technical", "ActiveDirectory"}, "Corporate_IT", NodeTypeTechnical, "Corporate IT systems"},
	{"Corp_Email", []string{"Technical", "Email"}, "Corporate_IT", NodeTypeTechnical, "Corporate IT systems"},
	{"Corp_ERP", []string{"Technical", "ERP"}, "Corporate_IT", NodeTypeTechnical, "Corporate IT systems"},
	{"Corp_VPN", []string{"Technical", "VPN"}, "Corporate_IT", NodeTypeTechnical, "Corporate IT systems"},

	// Interconnection (8)
	{"IX_Peering", []string{"Technical", "InternetExchange"}, "Interconnection", NodeTypeTechnical, "Sector interconnection"},
	{"Gateway_Internet", []string{"Technical", "Gateway"}, "Interconnection", NodeTypeTechnical, "Sector interconnection"},
	{"Gateway_Banking", []string{"Technical", "Gateway"}, "Interconnection", NodeTypeTechnical, "Sector interconnection"},
	{"Gateway_Emergency", []string{"Technical", "Gateway"}, "Interconnection", NodeTypeTechnical, "Sector interconnection"},
	{"Gateway_Healthcare", []string{"Technical", "Gateway"}, "Interconnection", NodeTypeTechnical, "Sector interconnection"},
	{"Gateway_Transport", []string{"Technical", "Gateway"}, "Interconnection", NodeTypeTechnical, "Sector interconnection"},
	{"Gateway_Energy", []string{"Technical", "Gateway"}, "Interconnection", NodeTypeTechnical, "Sector interconnection"},
	{"SIP_Trunk_Emergency", []string{"Technical", "SIP"}, "Interconnection", NodeTypeTechnical, "Sector interconnection"},

	// Human Nodes (22)
	{"Senior_Network_Eng", []string{"Human", "Engineer"}, "Human", NodeTypeHuman, "Senior Network Engineer"},
	{"IP_Engineer", []string{"Human", "Engineer"}, "Human", NodeTypeHuman, "IP/MPLS Engineer"},
	{"Mobile_Engineer", []string{"Human", "Engineer"}, "Human", NodeTypeHuman, "Mobile Core Engineer"},
	{"Optical_Engineer", []string{"Human", "Engineer"}, "Human", NodeTypeHuman, "Optical Transport Engineer"},
	{"NOC_Shift_Lead", []string{"Human", "NOC"}, "Human", NodeTypeHuman, "NOC Shift Leader"},
	{"NOC_Operator_1", []string{"Human", "NOC"}, "Human", NodeTypeHuman, "NOC Operator"},
	{"NOC_Operator_2", []string{"Human", "NOC"}, "Human", NodeTypeHuman, "NOC Operator"},
	{"NOC_Security_Analyst", []string{"Human", "Security"}, "Human", NodeTypeHuman, "Security Analyst"},
	{"NOC_Manager", []string{"Human", "Manager"}, "Human", NodeTypeHuman, "NOC Manager"},
	{"Network_Director", []string{"Human", "Director"}, "Human", NodeTypeHuman, "Network Operations Director"},
	{"CTO", []string{"Human", "Executive"}, "Human", NodeTypeHuman, "Chief Technology Officer"},
	{"Security_Manager", []string{"Human", "Manager"}, "Human", NodeTypeHuman, "Security Manager"},
	{"Field_Tech_1", []string{"Human", "FieldTech"}, "Human", NodeTypeHuman, "Field Technician"},
	{"Field_Tech_2", []string{"Human", "FieldTech"}, "Human", NodeTypeHuman, "Field Technician"},
	{"BSS_Admin", []string{"Human", "Admin"}, "Human", NodeTypeHuman, "BSS/OSS Administrator"},
	{"IT_Admin_Corp", []string{"Human", "Admin"}, "Human", NodeTypeHuman, "Corporate IT Admin"},
	{"Vendor_Ericsson", []string{"Human", "Vendor"}, "Human", NodeTypeHuman, "Ericsson Support Engineer"},
	{"Vendor_Cisco", []string{"Human", "Vendor"}, "Human", NodeTypeHuman, "Cisco TAC Engineer"},
	{"Vendor_Nokia", []string{"Human", "Vendor"}, "Human", NodeTypeHuman, "Nokia Optical Support"},
	{"Managed_SOC_Analyst", []string{"Human", "ManagedService"}, "Human", NodeTypeHuman, "Managed SOC Analyst"},
	{"Banking_Liaison", []string{"Human", "Liaison"}, "Human", NodeTypeHuman, "Banking Sector Account Manager"},
	{"Emergency_Liaison", []string{"Human", "Liaison"}, "Human", NodeTypeHuman, "Emergency Services Liaison"},

	// Process Nodes (8)
	{"Change_Advisory_Board", []string{"Process", "ChangeManagement"}, "Process", NodeTypeProcess, "Change advisory board"},
	{"Incident_Mgmt_Process", []string{"Process", "IncidentManagement"}, "Process", NodeTypeProcess, "Incident management process"},
	{"Vendor_Access_Control", []string{"Process", "VendorManagement"}, "Process", NodeTypeProcess, "Vendor remote access governance"},
	{"Patch_Management", []string{"Process", "PatchManagement"}, "Process", NodeTypeProcess, "Patch management process"},
	{"Capacity_Planning", []string{"Process", "CapacityPlanning"}, "Process", NodeTypeProcess, "Capacity planning process"},
	{"Disaster_Recovery", []string{"Process", "DisasterRecovery"}, "Process", NodeTypeProcess, "Disaster recovery process"},
	{"Regulatory_Compliance", []string{"Process", "Compliance"}, "Process", NodeTypeProcess, "ACMA/critical infrastructure obligations"},
	{"SLA_Management", []string{"Process", "SLA"}, "Process", NodeTypeProcess, "Service level agreement monitoring"},

	// External Sector Nodes (18)
	// Banking (4)
	{"Bank_ATM_Network", []string{"External", "Banking"}, "Sector_Banking", NodeTypeExternal, "Banking infrastructure"},
	{"Bank_Branch_WAN", []string{"External", "Banking"}, "Sector_Banking", NodeTypeExternal, "Banking infrastructure"},
	{"Bank_Trading_Floor", []string{"External", "Banking"}, "Sector_Banking", NodeTypeExternal, "Banking infrastructure"},
	{"Bank_SWIFT_Gateway", []string{"External", "Banking"}, "Sector_Banking", NodeTypeExternal, "Banking infrastructure"},
	// Emergency (5)
	{"Triple_Zero_Centre", []string{"External", "Emergency"}, "Sector_Emergency", NodeTypeExternal, "Emergency services"},
	{"CAD_System", []string{"External", "Emergency"}, "Sector_Emergency", NodeTypeExternal, "Emergency services"},
	{"Police_Radio_GW", []string{"External", "Emergency"}, "Sector_Emergency", NodeTypeExternal, "Emergency services"},
	{"Fire_Dispatch", []string{"External", "Emergency"}, "Sector_Emergency", NodeTypeExternal, "Emergency services"},
	{"Ambulance_Dispatch", []string{"External", "Emergency"}, "Sector_Emergency", NodeTypeExternal, "Emergency services"},
	// Healthcare (3)
	{"Hospital_Network", []string{"External", "Healthcare"}, "Sector_Healthcare", NodeTypeExternal, "Healthcare infrastructure"},
	{"Telehealth_Platform", []string{"External", "Healthcare"}, "Sector_Healthcare", NodeTypeExternal, "Healthcare infrastructure"},
	{"Pathology_WAN", []string{"External", "Healthcare"}, "Sector_Healthcare", NodeTypeExternal, "Healthcare infrastructure"},
	// Transport (3)
	{"Rail_SCADA_Comms", []string{"External", "Transport"}, "Sector_Transport", NodeTypeExternal, "Transport infrastructure"},
	{"Traffic_Mgmt_System", []string{"External", "Transport"}, "Sector_Transport", NodeTypeExternal, "Transport infrastructure"},
	{"Port_Operations", []string{"External", "Transport"}, "Sector_Transport", NodeTypeExternal, "Transport infrastructure"},
	// Energy (3)
	{"Grid_SCADA_Comms", []string{"External", "Energy"}, "Sector_Energy", NodeTypeExternal, "Energy infrastructure"},
	{"Gas_Pipeline_Comms", []string{"External", "Energy"}, "Sector_Energy", NodeTypeExternal, "Energy infrastructure"},
	{"Substation_Comms", []string{"External", "Energy"}, "Sector_Energy", NodeTypeExternal, "Energy infrastructure"},
}

// EdgeGroup groups edges by their type for cleaner iteration.
type EdgeGroup struct {
	EdgeType string
	Edges    [][2]string
}

// TelecomEdgeGroups organizes all 253 edges by type.
var TelecomEdgeGroups = []EdgeGroup{
	{"BACKBONE", [][2]string{
		{"Core_Router_SYD", "DWDM_SYD_MEL"},
		{"Core_Router_SYD", "DWDM_SYD_BNE"},
		{"Core_Router_SYD", "Core_Router_MEL"},
		{"Core_Router_SYD", "Core_Router_BNE"},
		{"Core_Router_MEL", "DWDM_SYD_MEL"},
		{"Core_Router_MEL", "DWDM_MEL_ADL"},
		{"Core_Router_BNE", "DWDM_SYD_BNE"},
		{"Core_Router_PER", "DWDM_ADL_PER"},
		{"Core_Router_ADL", "DWDM_MEL_ADL"},
		{"Core_Router_ADL", "DWDM_ADL_PER"},
	}},
	{"MOBILE_CORE", [][2]string{
		{"Core_Router_SYD", "PGW_Primary"},
		{"Core_Router_SYD", "MME_Primary"},
		{"Core_Router_MEL", "PGW_Secondary"},
		{"Core_Router_MEL", "MME_Secondary"},
		{"MME_Primary", "SGW_Primary"},
		{"MME_Primary", "HSS_Primary"},
		{"MME_Secondary", "SGW_Secondary"},
		{"MME_Secondary", "HSS_Primary"},
		{"SGW_Primary", "PGW_Primary"},
		{"SGW_Primary", "IMS_Core"},
		{"SGW_Secondary", "PGW_Secondary"},
		{"IMS_Core", "SIP_Trunk_Emergency"},
	}},
	{"ACCESS", [][2]string{
		{"Core_Router_SYD", "Exchange_CBD"},
		{"Core_Router_SYD", "Exchange_North"},
		{"Core_Router_SYD", "Exchange_South"},
		{"Core_Router_SYD", "Exchange_West"},
		{"Core_Router_SYD", "Exchange_Industrial"},
		{"MME_Primary", "Cell_CBD_1"},
		{"MME_Primary", "Cell_CBD_2"},
		{"MME_Primary", "Cell_CBD_3"},
		{"MME_Primary", "Cell_Suburban_1"},
		{"MME_Primary", "Cell_Hospital"},
		{"MME_Primary", "Cell_Emergency_HQ"},
		{"MME_Secondary", "Cell_Suburban_2"},
		{"MME_Secondary", "Cell_Regional_1"},
		{"MME_Secondary", "Cell_Regional_2"},
		{"Exchange_CBD", "Cell_CBD_1"},
		{"Exchange_CBD", "Cell_CBD_2"},
		{"Exchange_CBD", "Cell_CBD_3"},
		{"Exchange_CBD", "Cell_Emergency_HQ"},
		{"Exchange_CBD", "FDH_CBD"},
		{"Exchange_CBD", "FDH_Gov_Precinct"},
		{"Exchange_North", "Cell_Suburban_1"},
		{"Exchange_North", "FDH_Business_Park"},
		{"Exchange_South", "Cell_Suburban_2"},
		{"Exchange_South", "Cell_Hospital"},
		{"Exchange_South", "FDH_Hospital"},
		{"Exchange_West", "Cell_Regional_1"},
		{"Exchange_West", "Cell_Regional_2"},
		{"Exchange_Industrial", "FDH_Data_Centre"},
	}},
	{"MANAGEMENT", [][2]string{
		{"Core_Router_SYD", "NMS_Primary"},
		{"Core_Router_SYD", "Performance_Monitor"},
		{"NMS_Primary", "NMS_Secondary"},
		{"NMS_Primary", "NOC_Dashboard"},
		{"NMS_Primary", "Fault_Mgmt_System"},
		{"NMS_Primary", "Performance_Monitor"},
		{"NMS_Primary", "SIEM_Telecom"},
		{"NMS_Secondary", "NOC_Dashboard"},
		{"SIEM_Telecom", "Corp_Firewall"},
		{"SIEM_Telecom", "AAA_Server"},
		{"SIEM_Telecom", "Security_Manager"},
		{"Fault_Mgmt_System", "NOC_Dashboard"},
		{"Fault_Mgmt_System", "Ticketing_System"},
		{"NOC_Dashboard", "Ticketing_System"},
		{"Ticketing_System", "Workforce_Mgmt"},
		{"Corp_Email", "CTO"},
		{"Corp_ERP", "CTO"},
		{"NOC_Shift_Lead", "NOC_Manager"},
		{"Security_Manager", "CTO"},
		{"Security_Manager", "Regulatory_Compliance"},
		{"Security_Manager", "Vendor_Access_Control"},
		{"Security_Manager", "Patch_Management"},
		{"CTO", "Network_Director"},
		{"CTO", "NOC_Manager"},
		{"CTO", "Change_Advisory_Board"},
		{"CTO", "Regulatory_Compliance"},
		{"NOC_Manager", "Network_Director"},
		{"NOC_Manager", "Incident_Mgmt_Process"},
		{"NOC_Manager", "SLA_Management"},
		{"Network_Director", "Change_Advisory_Board"},
		{"Network_Director", "Capacity_Planning"},
		{"Network_Director", "Disaster_Recovery"},
	}},
	{"BSS_OSS", [][2]string{
		{"Core_Router_SYD", "DNS_Primary"},
		{"Core_Router_SYD", "AAA_Server"},
		{"Core_Router_SYD", "RADIUS_Server"},
		{"Core_Router_MEL", "DNS_Secondary"},
		{"NMS_Primary", "Provisioning_System"},
		{"Billing_System", "CRM_System"},
		{"Billing_System", "Provisioning_System"},
		{"CRM_System", "Corp_ERP"},
		{"Provisioning_System", "Inventory_System"},
		{"Inventory_System", "Workforce_Mgmt"},
		{"DNS_Primary", "DNS_Secondary"},
		{"AAA_Server", "RADIUS_Server"},
	}},
	{"CORPORATE", [][2]string{
		{"Core_Router_SYD", "Corp_Firewall"},
		{"Corp_Firewall", "IT_Switch_Core"},
		{"Corp_Firewall", "Corp_VPN"},
		{"Corp_AD", "IT_Switch_Core"},
		{"Corp_Email", "IT_Switch_Core"},
		{"Corp_ERP", "IT_Switch_Core"},
	}},
	{"INTERCONNECTION", [][2]string{
		{"Core_Router_SYD", "IX_Peering"},
		{"Core_Router_SYD", "Gateway_Internet"},
		{"Core_Router_SYD", "Gateway_Banking"},
		{"Core_Router_SYD", "Gateway_Emergency"},
		{"Core_Router_SYD", "Gateway_Healthcare"},
		{"Core_Router_SYD", "Gateway_Transport"},
		{"Core_Router_SYD", "Gateway_Energy"},
		{"Core_Router_MEL", "IX_Peering"},
		{"Exchange_Industrial", "Gateway_Transport"},
		{"Exchange_Industrial", "Gateway_Energy"},
		{"FDH_CBD", "Gateway_Banking"},
		{"FDH_Business_Park", "Gateway_Banking"},
		{"FDH_Hospital", "Gateway_Healthcare"},
		{"FDH_Gov_Precinct", "Gateway_Emergency"},
		{"IX_Peering", "Gateway_Internet"},
		{"Gateway_Emergency", "SIP_Trunk_Emergency"},
	}},
	{"SECTOR_DEPENDENCY", [][2]string{
		{"FDH_Hospital", "Hospital_Network"},
		{"Gateway_Banking", "Bank_ATM_Network"},
		{"Gateway_Banking", "Bank_Branch_WAN"},
		{"Gateway_Banking", "Bank_Trading_Floor"},
		{"Gateway_Banking", "Bank_SWIFT_Gateway"},
		{"Gateway_Emergency", "Triple_Zero_Centre"},
		{"Gateway_Emergency", "CAD_System"},
		{"Gateway_Emergency", "Police_Radio_GW"},
		{"Gateway_Healthcare", "Hospital_Network"},
		{"Gateway_Healthcare", "Telehealth_Platform"},
		{"Gateway_Healthcare", "Pathology_WAN"},
		{"Gateway_Transport", "Rail_SCADA_Comms"},
		{"Gateway_Transport", "Traffic_Mgmt_System"},
		{"Gateway_Transport", "Port_Operations"},
		{"Gateway_Energy", "Grid_SCADA_Comms"},
		{"Gateway_Energy", "Gas_Pipeline_Comms"},
		{"Gateway_Energy", "Substation_Comms"},
		{"SIP_Trunk_Emergency", "Triple_Zero_Centre"},
		{"CAD_System", "Fire_Dispatch"},
		{"CAD_System", "Ambulance_Dispatch"},
	}},
	{EdgeTypeHumanAccess, [][2]string{
		{"Core_Router_SYD", "Senior_Network_Eng"},
		{"Core_Router_SYD", "IP_Engineer"},
		{"Core_Router_MEL", "Senior_Network_Eng"},
		{"Core_Router_MEL", "IP_Engineer"},
		{"Core_Router_BNE", "Senior_Network_Eng"},
		{"Core_Router_BNE", "IP_Engineer"},
		{"Core_Router_PER", "IP_Engineer"},
		{"Core_Router_ADL", "IP_Engineer"},
		{"DWDM_SYD_MEL", "Optical_Engineer"},
		{"DWDM_SYD_BNE", "Optical_Engineer"},
		{"DWDM_MEL_ADL", "Optical_Engineer"},
		{"DWDM_ADL_PER", "Optical_Engineer"},
		{"MME_Primary", "Senior_Network_Eng"},
		{"MME_Primary", "Mobile_Engineer"},
		{"MME_Secondary", "Senior_Network_Eng"},
		{"MME_Secondary", "Mobile_Engineer"},
		{"SGW_Primary", "Mobile_Engineer"},
		{"SGW_Secondary", "Mobile_Engineer"},
		{"PGW_Primary", "Mobile_Engineer"},
		{"HSS_Primary", "Mobile_Engineer"},
		{"IMS_Core", "Mobile_Engineer"},
		{"Exchange_CBD", "Senior_Network_Eng"},
		{"Exchange_CBD", "Field_Tech_1"},
		{"Exchange_North", "Field_Tech_1"},
		{"Exchange_South", "Field_Tech_2"},
		{"Exchange_West", "Field_Tech_2"},
		{"Cell_CBD_1", "Field_Tech_1"},
		{"Cell_CBD_2", "Field_Tech_1"},
		{"Cell_Suburban_1", "Field_Tech_1"},
		{"Cell_Suburban_2", "Field_Tech_2"},
		{"Cell_Regional_1", "Field_Tech_2"},
		{"Cell_Regional_2", "Field_Tech_2"},
		{"NMS_Primary", "Senior_Network_Eng"},
		{"NMS_Primary", "NOC_Shift_Lead"},
		{"SIEM_Telecom", "NOC_Security_Analyst"},
		{"Fault_Mgmt_System", "Senior_Network_Eng"},
		{"Fault_Mgmt_System", "NOC_Shift_Lead"},
		{"Fault_Mgmt_System", "NOC_Operator_1"},
		{"Fault_Mgmt_System", "NOC_Operator_2"},
		{"NOC_Dashboard", "NOC_Shift_Lead"},
		{"NOC_Dashboard", "NOC_Operator_1"},
		{"NOC_Dashboard", "NOC_Operator_2"},
		{"NOC_Dashboard", "NOC_Security_Analyst"},
		{"Ticketing_System", "NOC_Shift_Lead"},
		{"Ticketing_System", "NOC_Operator_1"},
		{"Ticketing_System", "NOC_Operator_2"},
		{"Billing_System", "BSS_Admin"},
		{"CRM_System", "BSS_Admin"},
		{"Provisioning_System", "Senior_Network_Eng"},
		{"Provisioning_System", "BSS_Admin"},
		{"Inventory_System", "BSS_Admin"},
		{"Workforce_Mgmt", "Field_Tech_1"},
		{"Workforce_Mgmt", "Field_Tech_2"},
		{"DNS_Primary", "Senior_Network_Eng"},
		{"AAA_Server", "Senior_Network_Eng"},
		{"AAA_Server", "IP_Engineer"},
		{"Corp_Firewall", "IT_Admin_Corp"},
		{"Corp_AD", "IT_Admin_Corp"},
		{"Corp_Email", "IT_Admin_Corp"},
		{"Corp_VPN", "Senior_Network_Eng"},
		{"Corp_VPN", "IT_Admin_Corp"},
		{"IT_Switch_Core", "IT_Admin_Corp"},
		{"Gateway_Banking", "Senior_Network_Eng"},
		{"Gateway_Emergency", "Senior_Network_Eng"},
		{"NOC_Shift_Lead", "Senior_Network_Eng"},
		{"NOC_Shift_Lead", "NOC_Operator_1"},
		{"NOC_Shift_Lead", "NOC_Operator_2"},
		{"NOC_Shift_Lead", "NOC_Security_Analyst"},
		{"NOC_Shift_Lead", "Incident_Mgmt_Process"},
		{"NOC_Security_Analyst", "Security_Manager"},
		{"NOC_Security_Analyst", "Incident_Mgmt_Process"},
		{"Senior_Network_Eng", "Change_Advisory_Board"},
		{"Senior_Network_Eng", "Incident_Mgmt_Process"},
		{"Senior_Network_Eng", "Vendor_Access_Control"},
		{"Senior_Network_Eng", "Capacity_Planning"},
		{"Senior_Network_Eng", "Disaster_Recovery"},
		{"Senior_Network_Eng", "IP_Engineer"},
		{"Senior_Network_Eng", "Mobile_Engineer"},
		{"Senior_Network_Eng", "Optical_Engineer"},
		{"Senior_Network_Eng", "Vendor_Ericsson"},
		{"Senior_Network_Eng", "Vendor_Cisco"},
		{"Senior_Network_Eng", "Vendor_Nokia"},
		{"Senior_Network_Eng", "Network_Director"},
		{"Senior_Network_Eng", "CTO"},
		{"Senior_Network_Eng", "Emergency_Liaison"},
		{"Senior_Network_Eng", "Banking_Liaison"},
		{"IP_Engineer", "Change_Advisory_Board"},
		{"Mobile_Engineer", "Change_Advisory_Board"},
		{"Optical_Engineer", "Change_Advisory_Board"},
		{"IT_Admin_Corp", "Patch_Management"},
		{"BSS_Admin", "SLA_Management"},
		{"BSS_Admin", "Patch_Management"},
	}},
	{"VENDOR_ACCESS", [][2]string{
		{"Core_Router_SYD", "Vendor_Cisco"},
		{"Core_Router_MEL", "Vendor_Cisco"},
		{"DWDM_SYD_MEL", "Vendor_Nokia"},
		{"DWDM_SYD_BNE", "Vendor_Nokia"},
		{"MME_Primary", "Vendor_Ericsson"},
		{"MME_Secondary", "Vendor_Ericsson"},
		{"HSS_Primary", "Vendor_Ericsson"},
		{"SIEM_Telecom", "Managed_SOC_Analyst"},
		{"Corp_VPN", "Vendor_Ericsson"},
		{"Corp_VPN", "Vendor_Cisco"},
		{"Corp_VPN", "Vendor_Nokia"},
		{"Corp_VPN", "Managed_SOC_Analyst"},
		{"Security_Manager", "Managed_SOC_Analyst"},
		{"Vendor_Ericsson", "Vendor_Access_Control"},
		{"Vendor_Cisco", "Vendor_Access_Control"},
		{"Vendor_Nokia", "Vendor_Access_Control"},
		{"Managed_SOC_Analyst", "Vendor_Access_Control"},
	}},
	{"LIAISON", [][2]string{
		{"CRM_System", "Banking_Liaison"},
		{"Gateway_Banking", "Banking_Liaison"},
		{"Gateway_Emergency", "Emergency_Liaison"},
		{"SIP_Trunk_Emergency", "Emergency_Liaison"},
		{"Banking_Liaison", "SLA_Management"},
		{"Banking_Liaison", "Incident_Mgmt_Process"},
		{"Emergency_Liaison", "Incident_Mgmt_Process"},
		{"Emergency_Liaison", "Regulatory_Compliance"},
	}},
}

// TelecomNodesWithoutSeniorEng returns nodes filtered to exclude Senior_Network_Eng.
func TelecomNodesWithoutSeniorEng() []NodeDef {
	const excludeNode = "Senior_Network_Eng"
	result := make([]NodeDef, 0, len(TelecomProviderNodes)-1)
	for _, n := range TelecomProviderNodes {
		if n.Name != excludeNode {
			result = append(result, n)
		}
	}
	return result
}

// TelecomEdgeGroupsWithoutSeniorEng filters edge groups to exclude Senior_Network_Eng.
func TelecomEdgeGroupsWithoutSeniorEng() []EdgeGroup {
	const excludeNode = "Senior_Network_Eng"
	result := make([]EdgeGroup, 0, len(TelecomEdgeGroups))

	for _, group := range TelecomEdgeGroups {
		filteredEdges := make([][2]string, 0, len(group.Edges))
		for _, edge := range group.Edges {
			if edge[0] != excludeNode && edge[1] != excludeNode {
				filteredEdges = append(filteredEdges, edge)
			}
		}
		if len(filteredEdges) > 0 {
			result = append(result, EdgeGroup{
				EdgeType: group.EdgeType,
				Edges:    filteredEdges,
			})
		}
	}
	return result
}
